language: ruby
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
matrix:
  include:
  - rvm: 3.0.1
    env:
      - LABEL=docker_build_and_push
    services:
      - docker
    script:
      - chmod u+x ./build_and_deploy_to_dockerhub.sh
      - ./build_and_deploy_to_dockerhub.sh
