name: Source

on: [ push ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ./.github/actions/setup-ruby-1.71.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
